### ISSUE TITLE
RTL version of wp-cli.github.com

### ISSUE THREAD

**Issue by man4toman** [wp-cli/wp-cli.github.com#327]
I started translating the wp-cli website to Persian that is rtl support locale.
Is wp-cli website ready for rtl locale?

Here what I started:
https://github.com/man4toman/wp-cli.github.com/blob/master/fa/index.md

Should we do something more?

Thanks

**Comment by schlessera** [comment]
Thanks for creating this issue, @man4toman!

The current Jekyll theme does not yet support RTL: https://github.com/wp-cli/wp-cli.github.com/blob/master/assets/css/stylesheet.css

So, I'm trying to collect an overview of the tasks needed to make this happen, please correct me if I'm missing something:

- [ ] Add Jekyll config value to select RTL for a given language.
- [ ] Use Jekyll config in layouts to add `dir` ( and maybe `class` ) attribute(s) to `body` tag.
- [ ] Add CSS rules that override direction-specific properties based on said `dir` or `class` attribute(s).

**Comment by man4toman** [comment]
Thanks @schlessera 
I check the tasks and I think it's good.

Please let me know if I can help, maybe I can create the rtl version of css rules.

**Comment by man4toman** [comment]
In addition, I think add a class attribute to body tag can be better solution, sometimes adding dir to body cause some problems in layout(I experienced this issue before).
